name: Bug
description: Something broken.
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: repro
    attributes:
      label: Repro steps
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
